services:
  - type: web
    name: telegram-bot
    env: java
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: BOT_TOKEN
        fromSecret: true
        secret: RENDER_BOT_TOKEN
      - key: BOT_USERNAME
        fromSecret: true
      - key: PORT
        value: 8080